// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/81b951f1ac437d1eb5ff5171a0bfa6c467634b13/moment/moment.d.ts
declare var moment: moment.MomentStatic;
